### ISSUE TITLE
VR Area works on Quest 2, but machines themselves don't.

### ISSUE THREAD

**Issue by shwanpla** [derole1/MaiMai-VR#4]
Hello, first I want to say thanks for doing this, my arcade's been closed because of COVID so I've been missing this title. 

I was able to load into the area, but the game is overscanned to the machines and the buttons don't seem to do anything (the vibration feedback works, however).

I am using an Oculus Quest 2 and the built in Virtual Desktop.

https://user-images.githubusercontent.com/73059184/96365299-7cfdbb00-10f4-11eb-963e-ccc6e82f087b.png

Edit: I don't think the data corruption that the game says is part of the issue, it might be, Whenever I booted up the game to play via keyboard, I've been able to ignore the corruption and play the whole game without any issues.

**Comment by CuriousCod** [comment]
You need to disable 1P_ONLY in Groovemaster.ini.

Otherwise the game won't size properly to the cabs.

**Comment by shwanpla** [comment]
> You need to disable 1P_ONLY in Groovemaster.ini.
> 
> Otherwise the game won't size properly to the cabs.

This fixed the scaling issue. Thank you! 

the buttons seem to work, i didn't realize my windows all had to be minimized...

**Comment by CuriousCod** [comment]
The buttons only work when you have focus on the maimai.exe window.

Does the game run smoothly on your end? I get this weird jitter whenever I move my head when looking at the maimai game screen. I'm also using Quest 2 with VD. Didn't have this issue with CV1.

**Comment by shwanpla** [comment]
The game runs smooth enough for me, I haven't noticed any jitter but then again I'm moving alot on it. Also I am using a USB 2.0 connection for vrlink (I ordered a 15ft cable but for now I am using using a Nintendo switch Procon cable and a Google Pixel usb C adapter for a little bit more length at the cost of lower bandwidth). I play in 1080p with VR recommended settings. 

I'll let you know when I get the proper vrlink cable.
