### ISSUE TITLE
Im little bit confuse about the instruction anybody help?

### ISSUE THREAD

**Issue by abil34** [derole1/MaiMai-VR#5]
i dont get with the "2)	Change the “maimaidir.ini” file to match the directory of your maimai FiNALE EXE "
is that mean i extract the folder to the maimai data or something ?
![image](https://user-images.githubusercontent.com/81847300/113470269-813d4b00-947e-11eb-907b-4abd8abc564e.png)
sorry for asking ,some small brain issue

**Comment by abil34** [comment]
i got it fixed

**Comment by OliverLSanz** [comment]
Hey @abil34 how did you fix it? I've pasted the route to my local exe in that file, but does not work. Still says it does not find it.
