### ISSUE TITLE
Actually checkin the source code

### ISSUE THREAD

**Issue by dogtopus** [derole1/MaiMai-VR#7]
From README:

> I had a few people wonder why the code isnt actually in the github repo (Yes I do know how github works). This is because some of the files seem to be to large for the github repo (such as assets) and it refuses to let me upload them.

This is not a valid reason. GitHub offers [LFS](https://git-lfs.github.com/) which gives you 1GB of space shared across all projects. The project with assets are way less than 1GB so it should fit properly.

See also https://www.toptal.com/developers/gitignore/api/unity for a proper `.gitignore` file for Unity projects.

**Comment by derole1** [comment]
I dont really maintain this repo much anymore since its an old project, but I will try to look into this if I find the time to. Thanks for letting me know about this :D
